### ISSUE TITLE
ConnectClientAsync - Cannot access a disposed object.

### ISSUE THREAD

**Issue by JulanDeAlb** [TwitchLib/TwitchLib.Communication#30]
**Error:** 
I encounter the following Error using the WebSocketClient:
After a internet connection loss, the Client try to reconnect to Twitch BUT after the first attempt it will just straight up crash because the .NET ClientWebSocket disposes its inner WebSocket if it couldn't connect to the URL.

https://github.com/TwitchLib/TwitchLib.Communication/blob/9f1c6185a71231e1571662bc265dc4a96d80873f/src/TwitchLib.Communication/Clients/ClientBase.cs#L241-L258

In the given code above, every attempt to run OpenPrivateAsync() will lead to create a new Client, but then enters the loop where it stays even if it didn't connected successfully, trying to connect with a disposed inner WebSocket.

**Easy Reproduction:** 
Disconnect your PC from the Internet and run
```csharp
var client = new TwitchClient(loggerFactory: factory);
client.Initialize(new ConnectionCredentials(...));

client.ConnectAsync();
Console.ReadKey();
```

**Possible Solution:**
Move line 241 into the while loop
```csharp
while (!IsConnected &&  !Options.ReconnectionPolicy.AreAttemptsComplete())
{
                Logger?.TraceAction(GetType(), "try to connect");
                
                // Always create new client when opening new connection
                Client = CreateClient();
                
                if (!first)
                {
                    await Task.Delay(Options.ReconnectionPolicy.GetReconnectInterval(), CancellationToken.None);
                }
```

**Comment by AoshiW** [comment]
this issue has been resolved by #32 , so it can be closed
